# Generated by Django 5.0.6 on 2024-08-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_comment_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
